// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHoPnUH33tkB0hEDZB6ZkoS8BadCVDfiY',
    appId: '1:513237028615:web:b47f63781bddf41dd8ffa2',
    messagingSenderId: '513237028615',
    projectId: 'quiz-app-ffbcc',
    authDomain: 'quiz-app-ffbcc.firebaseapp.com',
    storageBucket: 'quiz-app-ffbcc.firebasestorage.app',
    measurementId: 'G-4FKB5SDSM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvoCbRXftGWIS3UqO1U5sellq01YCs-k',
    appId: '1:513237028615:android:7544243f86f56344d8ffa2',
    messagingSenderId: '513237028615',
    projectId: 'quiz-app-ffbcc',
    storageBucket: 'quiz-app-ffbcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkknF_-MQSc4z45oBX7OSFYYSy9SMZHyY',
    appId: '1:513237028615:ios:e64b77e50c04095fd8ffa2',
    messagingSenderId: '513237028615',
    projectId: 'quiz-app-ffbcc',
    storageBucket: 'quiz-app-ffbcc.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkknF_-MQSc4z45oBX7OSFYYSy9SMZHyY',
    appId: '1:513237028615:ios:e64b77e50c04095fd8ffa2',
    messagingSenderId: '513237028615',
    projectId: 'quiz-app-ffbcc',
    storageBucket: 'quiz-app-ffbcc.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHoPnUH33tkB0hEDZB6ZkoS8BadCVDfiY',
    appId: '1:513237028615:web:59814803a0759c60d8ffa2',
    messagingSenderId: '513237028615',
    projectId: 'quiz-app-ffbcc',
    authDomain: 'quiz-app-ffbcc.firebaseapp.com',
    storageBucket: 'quiz-app-ffbcc.firebasestorage.app',
    measurementId: 'G-RVWMNNGCS1',
  );
}
