// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;

/// NOTE: Replace these with your actual Firebase config values generated by
/// `flutterfire configure`. These placeholders let the app compile.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return FirebaseOptions(
        apiKey: 'AIza...web-api-key',
        appId: '1:000:web:xxxxxxxxxxxx',
        messagingSenderId: '000000000000',
        projectId: 'your-project-id',
        authDomain: 'your-project-id.firebaseapp.com',
        storageBucket: 'your-project-id.appspot.com',
        measurementId: 'G-XXXXXXX',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: 'AIza...android-api-key',
          appId: '1:000:android:xxxxxxxxxxxx',
          messagingSenderId: '000000000000',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return FirebaseOptions(
          apiKey: 'AIza...ios-api-key',
          appId: '1:000:ios:xxxxxxxxxxxx',
          messagingSenderId: '000000000000',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
          iosBundleId: 'com.example.app',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        // Desktop placeholder (won't be used for real Firebase desktop config)
        return FirebaseOptions(
          apiKey: 'AIza...desktop-api-key',
          appId: '1:000:desktop:xxxxxxxxxxxx',
          messagingSenderId: '000000000000',
          projectId: 'your-project-id',
          storageBucket: 'your-project-id.appspot.com',
        );
    }
  }
}
